### ISSUE TITLE
Build Agent Pool incorrectly queuing on Hosted agent pool.

### ISSUE THREAD

**Issue by virasana** [libgit2/libgit2sharp#1640]
### Reproduction steps
- Log on to VSTS
- Navigate to Pipelines | Build
- Create a new build definition with one build task - e.g. a bash command-line task to echo "hello"
- Under Tasks | Pipeline, select a custom Agent Pool - "MyAgentPool"
- Save and Queue
- Queue the build on anything but the the hosted pool
- Result: FAIL!  It always selects Hosted!

Have a look at the generated yaml (Build Definition | Tasks | Pipeline | View Yaml)--> it is saving it as Hosted in the yaml, even though the web portal is otherwise showing my custom build agent pool.

```
resources:
- repo: self
queue:
  name: **Hosted** <== INCORRECT
steps:
- bash: './streact/build-and-push.bat'
  displayName: 'Build and Push streact'
```

### Expected behavior
It should queue on the selected agent pool, and not the Hosted pool.

### Actual behavior
It always selects "Hosted"

### Operating system(s) tested; .NET runtime tested
Hosted Linux preview, Hosted Ubuntu 1604
