### ISSUE TITLE
LibGit2Sharp.Core.Proxy.git_commit_tree_id throws NullReferenceException in shallow clones

### ISSUE THREAD

**Issue by AArnott** [libgit2/libgit2sharp#1775]
### Reproduction steps

```
dotnet tool install -g nbgv
git clone https://github.com/aarnott/nerdbank.streams  --depth 10
cd .\nerdbank.streams\
nbgv get-version

### Expected behavior

An exception thrown explaining that data is missing because of a shallow clone.

### Actual behavior

A NullReferenceException that does not suggest the underlying problem.

### Version of LibGit2Sharp (release number or SHA1)

0.27.0-preview.7+gd47cfd9144.libgit2-572e4d8

### Operating system(s) tested; .NET runtime tested

Windows 10. .NET Core

**Comment by olivier-spinelli** [comment]
In addition to the better exception you suggest, I'd love to benefit of a simple `bool IsShallowed {get; }` or `IsInvalid` or IsOutOfClone` that would avoid an awful try/catch.

**Comment by vincentcastagna** [comment]
We are still experiencing this issue wit git version 5.10.0 on azure devops pipeline.

The fix is to specify a max depth of 0 with a checkout task before gitversion : 

```yml
steps:
- checkout: self 
  fetchDepth: 0  
  clean: true
  
- task: gitversion/setup@0
  inputs:
    versionSpec: '5.10.1'
  displayName: 'Install GitVersion'
  ```
